export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const MOVIES_ERROR = 'MOVIES_ERROR';


export const MOVIESLIST_LOADING = 'MOVIESLIST_LOADING';
export const MOVIESLIST_SUCCESS = 'MOVIESLIST_SUCCESS';
export const MOVIESLIST_ERROR = 'MOVIESLIST_ERROR';
